name: Publish Image on DockerHub on main branch push

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

        
    steps:
    # Comprueba repo
    - name: Check repo
      uses: actions/checkout@v2
    # Login into DockerHub
    - name: Login DockerHub
      uses: docker/login-action@v1.10.0
      with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
    # Construcción y push a Dockerhub. Utilizarmos algún action del marketplace como
    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_USER}}/charge-your-travel:latest
    
    

